AethysRotation/Main.lua, AethysRotation_Mage/Frost.lua
Check AethysCore PRs for required changes to pets to get water elemental working correctly. This could likely use a bit more love still but it's quite passable and with 7.2.5 changing our fundamental play not sure worth getting perfect for the moment.
=> [Frost] Mage Initial implementation

AethysRotation/Main.lua, AethysRotation_DeathKnight/AethysRotation_DeathKnight.toc, AethysRotation_DeathKnight/Unholy.lua
TODO:
-opener
-Castigator rotation
-tweaks and bugfixes (mostly related to rp costs of spells)
=> Initial UnholyDK support

AethysRotation_Rogue/Subtlety.lua
* Add an optional parameter to the Finish() function to allow StealthMacro() to pass in which stealth spell will be up for the Finisher
=> [Subtlety] Fix Stealth Macro Finisher Predictions

AethysRotation/Main.lua, AethysRotation_Druid/Feral.lua
Adds a rotation for Feral Druid.
Please note that this is the first time ever working in Lua, and on a WoW addon. As I have not tested this, there may be mistakes, however as there were only adjustments made from the original file, it _should_ be fine.
=> Feral Druid

AethysRotation_Druid/Feral.lua, AethysRotation_Druid/Settings.lua
Hope I did this right, new to the git thing.
Tried my hand at updating and extending the Feral.lua to be in line with the current APL. Includes updated Settings.lua necessary for the Feral.lua changes.
Did basic bugtesting on my druid and didn't find any major issues.
=> [Druid] Updated Feral.lua and Settings.lua

AethysRotation_Hunter/AethysRotation_Hunter.toc, AethysRotation_Hunter/Events.lua, AethysRotation_Hunter/Hunter.lua, AethysRotation_Hunter/Marksmanship.lua, AethysRotation_Hunter/Settings.lua
Using Volley and previously cast Multishots to determine how many Units a theoretical Multishot will hit.
This allows us to have Multishot as a Cast instead of a Cast suggested
=> Splash target count prediction

AethysRotation_DeathKnight/Frost.lua
the 'or' statements should be in separate brackets, or?
=> missing brackets?

symlink.sh
This symlink.sh file provides the commands necessary to symlink the repo files to the AddOns directory.
=> Symlinks to use AethysRotation with linux/macos

AethysRotation_DemonHunter/Havoc.lua, AethysRotation_DemonHunter/Settings.lua
Following the APL change 2 months ago : https://github.com/simulationcraft/simc/commit/e3724bb64630b234eb2d26ccd866ad7b4da0792d
=> [Havoc] Add Arcane Torrent to suggested casts

.gitignore, HeroRotation_DeathKnight/Frost.lua
- updated commented simc APL at the end of the file
- added range check for all abilities
- removed unused ColdHeart function. was implemented twice
- added *.swp to .gitignore. I don't want to add vim swap files :)
=> [Frost] improved range checks, removed unused function

HeroRotation_Paladin/Protection.lua
=> Change SpellID for Judgement

HeroRotation/Core.lua, HeroRotation/Settings.lua, HeroRotation/UI.lua
=> Added a setting to have a faded icon when not enough mana or energy.

HeroRotation/Main.lua, HeroRotation_Monk/Brewmaster.lua, HeroRotation_Warrior/HeroRotation_Warrior.toc, HeroRotation_Warrior/Overrides.lua, HeroRotation_Warrior/Protection.lua, HeroRotation_Warrior/Settings.lua
- Based upon BFA spec ability priority
- Includes option to include defensive and mitigation abilities
- Supports inline and off GCD concepts 
- Option/Setting to use Last Stand as a filler during Shield Block down time (Currently working on a more optimal version of this)
- Supports Vengence however I do not currently use this
- Incorporates Free Revenge Procs 
- Has a simple mechanism to prevent Rage cap based upon whether player is currently tanking or not
=> First iteration of Prot Warrior - Looking for feedback

HeroRotation/Main.lua, HeroRotation_Monk/Brewmaster.lua
- Fixed alignment of code
- Added better support for non English clients when attempting to determine Ignore Pain cap
=> Minor fixed based upon code review

HeroRotation_Mage/Arcane.lua
Current rotation does not enter stay in Burn Phase, Presence of Mind is suggested even though the buff is applied, final Arcane Blast does not detect lack of mana to be able to cast.
Also added debug messages
=> Fixed burn phase, added debug messages

HeroRotation_Warlock/Affliction.lua
Updated with Tier22 APL: 
1. Fixed UAS (thanks blackyTemp)
2. Init variables
3. Fixed Spell IDs
4. Not tested actual Azerite IDs in-game
5. Issue with pet resolved with pet check
6. Fixed contagion issue (Contagion still in SimC profile, but not in-game as of 8.0)
=> WinnerW - Updated WiP - Tested

HeroRotation_Warlock/Demonology.lua, HeroRotation_Warlock/Settings.lua
Works well enough for the current rotation, but until I can figure out pet tracking, I can't have it properly suggest Implosion or other parts of the APL that require a certain number of imps, etc.
=> [Demonology] WIP

HeroRotation_Mage/Arcane.lua
Current rotation stays in burn phase and never leaves
=> Stop burn phase plus debugging

HeroRotation_DeathKnight/Frost.lua
- Updated to newest APL
- if CDs are toggled off, skip the pooling rotation.
- replace IsCastableP with IsReadyP for GlacialAdvance to check also for runic power.
=> updated APL, fixed CD switch, fixed GlacialAdvance

HeroRotation_Paladin/Retribution.lua
changed WakeofAshes = Spell(255937), to correct Spell ID and added Inquisition = Spell(84963), and usage
=> Quick Fix for BFA

HeroRotation_DemonHunter/Vengeance.lua
- Updates for latest APL
-- Move Metamorphosis ahead of Fiery Brand in Defensives()
-- Change Soul Cleave handling to match current APL
-- Change Fracture handling to match current APL
-- Update commented SimC APL at bottom of file
=> [Vengeance] Update to Latest APL

HeroRotation_Hunter/Overrides.lua, HeroRotation_Hunter/Settings.lua
- Also removed options for Potion of Prolonged Power and Sephuz
interrupt
=> [Marksmanship] Added option for Lone Wolf

HeroRotation_DeathKnight/Frost.lua
- Update APL to include Icy Citadel azerite trait as per SimC's Jan 12
updates
=> [Frost DK] Include Icy Citadel Azerite Trait

HeroRotation_Warlock/Demonology.lua, HeroRotation_Warlock/Events.lua
=> [Demonology] Fix double casting and issue with ImpsSpawnedDuring
